version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD} # Set this in your .env file
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Grafana/datasource/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./Grafana/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./Grafana/temperature_dashboard.json:/etc/grafana/dashboards/temperature_dashboard.json


  temperature_api:
    build: ./get_temp_logic/
    container_name: temperature_api
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY} # Set this in your .env file

volumes:
  prom_data:
  grafana-data: