FROM python:3.9.23-alpine


# Set the working directory
WORKDIR /app

# Copy the script into the container
COPY tempAPI.py .

# Install required packages
RUN pip install requests prometheus_client

# Expose the port that the app runs on
EXPOSE 5000

# Command to run the application
CMD ["python", "tempAPI.py"]
